Auto Update: true
Chat:
   enabled: true
   format: "%vault_prefix_name_suffix% : "
   login: "&7[&a+&7]&r %playername%"
   leave: "&7[&c-&7]&r %playername%"
   clear: "Chat cleared by %playername%"
   Caps:
      Count: 4
      Message: "&aPlease do not use to much caps!"
   Swear:
      enable: true
      message: "&cPlease dont use that sort of language!"
      Words:
           - bastard
           - asshole
   mute:
      commands:
           - message
           - msg
           - m
           - tell
           - t
           - whisper
           - w
           - reply
           - r
           - me
           - say
Factions:
  Leader: "**"
  Officer: "*"
  Member: "+"
  Recruit: "-"
  Wilderness: "Wilderness"